@startuml
skinparam linetype ortho
skinparam nodesep 100

[Go Image Processor]
[Backend]
[Frontend]

cloud RabbitMQ
node FFmpeg
database "LibSQL"
database "Minio"

[Frontend] <--> [Backend] : HTTP Requests

[Backend] <--> [Minio] : S3 API
[Backend] <-r-> [LibSQL] : SQL
[Backend] -r-> [RabbitMQ] : Publishes
[RabbitMQ] -r-> [Go Image Processor] : Consumes

[Go Image Processor] --> [Backend] : HTTP Requests
[Go Image Processor] --> [FFmpeg] : Executes commands
[Go Image Processor] <-r-> [Minio] : S3 API

@enduml
